# Generated by Django 5.1.5 on 2025-01-27 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Emissora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=50)),
                ('time_casa', models.CharField(max_length=255)),
                ('time_casa_logo', models.URLField(blank=True, max_length=500, null=True)),
                ('time_visitante', models.CharField(max_length=255)),
                ('time_visitante_logo', models.URLField(blank=True, max_length=500, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='jogos.campeonato')),
                ('emissoras', models.ManyToManyField(related_name='jogos', to='jogos.emissora')),
            ],
        ),
    ]
