# Generated by Django 5.1.5 on 2025-01-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
