# Generated by Django 5.1.5 on 2025-01-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0003_jogo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='status',
            field=models.BooleanField(blank=True, default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='status',
            field=models.BooleanField(blank=True, default=True, max_length=50, null=True),
        ),
    ]
